global using AbstractFactory.Factories;
global using AbstractFactory.Services;
global using FactoryMethod.Services;
global using FactoryMethod.Factory;
global using Builder.Features;
global using Singleton.Features;
global using Adapter.Features;
global using Decorator.Features;
global using Decorator.Decorators;